version = 1

[merge]
automerge_label = "automerge"
require_automerge_label = true
delete_branch_on_merge = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["renovate"]

[approve]
auto_approve_usernames = ["renovate"]
