name: Register Provider
description: Add your provider to the OpenFeature documentation so others can discover and use it.
title: "[Provider]: "
labels:
  - provider
# assignees:
#   - open-feature/maintainers
body:
  - type: dropdown
    attributes:
      label: SDK
      description: What SDK does work with?
      multiple: false
      options:
        - Java
        - .NET
        - Golang
        - JavaScript/TypeScript
        - Python
        - Other (Not available in the list)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Vendor/Tool
      description: What vendor or tool does this provider integrate with?
      multiple: false
      options:
        - ConfigCat
        - DevCycle
        - Flagship
        - Flagsmith
        - Flipt
        - GO Feature Flag
        - GrowthBook
        - Harness
        - LaunchDarkly
        - PostHog
        - RemoteFlags
        - Split
        - Storytel
        - Unleash
        - Other (Not available in the list)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Maintainer
      description: Who is primarily responsible for maintenance?
      multiple: false
      options:
        - Vendor
        - Community
        - Other (Not available in the list)
    validations:
      required: true
  - type: input
    attributes:
      label: Repository
      description: A link to the repository that contains the provider's code.
      placeholder: https://github.com/open-feature/example-provider
  - type: textarea
    attributes:
      label: Artifacts
      description: Links to any published artifact.
      placeholder: |
        npm: https://www.npmjs.com/package/@openfeature/example-provider
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more ways to promote your provider!

        Tip: A black/white svg logo is helpful when a new vendor/tool.
    validations:
      required: false
